---
swagger: "2.0"
info:
  description: This is a simple API
  version: 1.0.0
  title: Simple Inventory API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: virtserver.swaggerhub.com
basePath: /wwxxvision/Ecommerce/1.0.0
tags:
- name: Public
  description: Публичное api
schemes:
- https
paths:
  /products:
    get:
      tags:
      - Public
      summary: Cписок товаров
      operationId: getProducts
      produces:
      - application/json
      parameters:
      - name: filterBy
        in: query
        description: Параметр по которому будем фильтровать продукты [Brand,  Rating, Price, Stock_Status, Tag, Attribute]
        required: false
        type: string
      - name: sortBy
        in: query
        description: Параметр по которому будем сортировать продукты [Price, Date, Rating]
        required: false
        type: string
      - name: limit
        in: query
        description: Лимит элементов на текущем запросе
        required: true
        type: integer
        maximum: 50
        minimum: 0
        format: int32
      - name: page
        in: query
        description: Показать элементы на текущей странице
        required: true
        type: integer
        format: int32
      responses:
        "200":
          description: Полученный список товаров
          schema:
            type: array
            items:
              $ref: '#/definitions/products'
        "400":
          description: Bad request
        "404":
          description: Not found
  /product:
    get:
      tags:
      - Public
      summary: Получить товар
      operationId: getProduct
      produces:
      - application/json
      parameters:
      - name: id
        in: query
        description: Параметр id по которому будем получать товар
        required: true
        type: integer
        format: id
      responses:
        "200":
          description: Полученный список товаров
          schema:
            type: array
            items:
              $ref: '#/definitions/product'
        "400":
          description: Bad request
        "404":
          description: Not found
definitions:
  products:
    type: object
    required:
    - brand
    - created
    - id
    - images
    - name
    - quantity
    - stock_status
    - thumb
    properties:
      id:
        type: number
        format: id
        example: 1.0
      created:
        type: number
        format: unix
        example: 12-01-2021UTC
      name:
        type: string
        example: Футболка Delo Wear Col.
      description:
        type: string
        example: Удобная футболка
        maxLength: 260
      quantity:
        type: integer
        format: int32
        example: 55
      stock_status:
        type: string
        example: in_stock | preorder | out_stock
        maxLength: 260
      brand:
        $ref: '#/definitions/brand'
      thumb:
        type: string
        format: uri
        example: http://domain.com/public/images/product/thumb
      images:
        $ref: '#/definitions/images'
  product:
    type: object
    required:
    - attributes
    - brand
    - created
    - id
    - images
    - name
    - quantity
    - stock_status
    - thumb
    - variants
    properties:
      id:
        type: number
        format: id
        example: 1.0
      created:
        type: number
        format: unix
        example: 12-01-2021UTC
      name:
        type: string
        example: Футболка Delo Wear Col.
      description:
        type: string
        example: Удобная футболка
        maxLength: 260
      quantity:
        type: integer
        format: int32
        example: 55
      stock_status:
        type: string
        example: in_stock | preorder | out_stock
        maxLength: 260
      brand:
        $ref: '#/definitions/brand'
      thumb:
        type: string
        format: uri
        example: http://domain.com/public/images/product/thumb
      images:
        $ref: '#/definitions/images'
      variants:
        $ref: '#/definitions/variants'
      attributes:
        $ref: '#/definitions/attributes'
  brand:
    required:
    - description
    - id
    - name
    properties:
      id:
        type: number
        format: id
        example: 1.0
      name:
        type: string
        example: Delo Wear
      description:
        type: string
        example: Хороший бренд одежды
        maxLength: 260
  images:
    type: array
    items:
      $ref: '#/definitions/images_inner'
  attributes:
    type: array
    items:
      $ref: '#/definitions/attributes_inner'
  variants:
    type: array
    items:
      $ref: '#/definitions/variants_inner'
  variants_values:
    type: array
    items:
      $ref: '#/definitions/variants_values_inner'
  images_inner:
    type: object
    properties:
      id:
        type: number
        format: id
        example: 1.0
      src:
        type: string
        format: uri
        example: http://domain.com/public/images/product
      order:
        type: number
        example: 1.0
  attributes_inner:
    type: object
    properties:
      id:
        type: number
        format: id
        example: 1.0
      name:
        type: string
        example: Цвет
        maxLength: 260
      type:
        type: string
        example: color | tableOfSizes | material
        maxLength: 260
      value:
        type: string
        example: Сининий
        maxLength: 260
  variants_inner:
    type: object
    properties:
      id:
        type: number
        format: id
        example: 1.0
      name:
        type: string
        example: Размер одежды
        maxLength: 260
      type:
        type: string
        example: select | radio
        maxLength: 260
      values:
        $ref: '#/definitions/variants_values'
  variants_values_inner:
    type: object
    properties:
      id:
        type: number
        format: id
        example: 1.0
      name:
        type: string
        example: "44"
        maxLength: 260
      price:
        type: number
        format: double
        example: 45.0
      quantity:
        type: integer
        format: int32
        example: 5
